source 'https://github.com/Huaixing/CATMasterRepos.git'

platform :ios, '10.0'

target 'CATPhotoKit_Example' do
  pod 'CATPhotoKit', :path => '../'
  pod 'CATCommonKit', '~> 0.1.5'

  target 'CATPhotoKit_Tests' do
    inherit! :search_paths

    
  end
end
