source 'https://github.com/Huaixing/CATMasterRepos.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'CATPhotoKit_Example' do
  pod 'CATPhotoKit', :path => '../'
  pod 'CATCommonKit', '~> 0.2.0'
  pod 'MBProgressHUD', '~> 1.2.0'

  target 'CATPhotoKit_Tests' do
    inherit! :search_paths

    
  end
end
